{% set name = "ashlar" %}
{% set version = "1.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ashlar-{{ version }}.tar.gz
  sha256: 3c4fb3a2d1ffee986f86c633d12f753544904ddccbd8499851badbdeec3142be

build:
  number: 0
  noarch: python
  entry_points:
    - ashlar=ashlar.scripts.ashlar:main
    - preview_slide=ashlar.scripts.preview_slide:main
    - make_alignment_movie=ashlar.scripts.make_alignment_movie:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
  run:
    - blessed >=1.17
    - ffmpeg >=5.1
    - matplotlib-base >=3.1.2
    - networkx >=2.4
    - numpy >=1.18.1
    - pyjnius >=1.2.1
    - python >=3.10
    - scikit-image >=0.19.2,<0.20
    - scikit-learn >=0.21.1
    - scipy >=1.4.1
    - tifffile >=2022.4.8
    - zarr >=2.11.3

test:
  imports:
    - ashlar
    - ashlar.scripts
  requires:
    - pip
  commands:
    - pip check
    - ashlar --help
    - preview_slide --help
    - make_alignment_movie --help
    - ashlar exemplar-001-cycle-06.ome.tiff
  files:
    - exemplar-001-cycle-06.ome.tiff
about:
  home: https://github.com/sorgerlab/ashlar
  summary: Alignment by Simultaneous Harmonization of Layer/Adjacency Registration
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RobJY
